#!/usr/bin/env python3
"""Generate the About page for bahansen.us."""
from pathlib import Path

import site_parts

OUT = Path("/opt/data/git/website/about.html")

PAGE = """{head}
{nav}
  <main class="container">
    <section class="briefing-header">
      <h1>About</h1>
      <p style="color:var(--text-dim);">Who's behind bahansen.us and how the Daily Security Intelligence Briefing is made.</p>
    </section>

    <div class="briefing-body">
      <div class="brief">bahansen.us is the personal site of Brett Hansen — a daily security intelligence briefing, home lab notes, and security research.</div>

      <h2>The Daily Security Intelligence Briefing</h2>
      <p>Every morning a fresh security briefing is published, cut through the noise to the signal that matters for operators. It is organized into three tiers:</p>
      <ul class="tag-list">
        <li><span class="tag-label">Tier 1</span> Priority targets — must-read items with sector/world-scale impact (mass-exploited zero-days, cloud-identity breaks, nation-state critical infrastructure).</li>
        <li><span class="tag-label">Tier 2</span> Essential intelligence — the default home for vulnerability news, patch notes, write-ups, and analysis.</li>
        <li><span class="tag-label">Tier 3</span> Industry noise — funding news, market speculation, and aging follow-ups worth a skim.</li>
      </ul>
      <p>Each edition carries an <em>Overall Daily Threat Level</em> (Critical / High / Moderate / Low) and a one-to-two sentence threat-vector summary at the top.</p>

      <h2>How it's made</h2>
      <p>The briefing is generated by an automated pipeline: a research pass pulls the day's security news, deduplicates it against prior coverage, and classifies each item into the tier structure above. It's assembled and delivered daily.</p>

      <h2>This site</h2>
      <p>A static site served from GitHub Pages — fast, secure, no tracking, no cookies. The full archive lives under <a href="history.html">History</a>.</p>
    </div>
  </main>
{footer}
</body>
</html>
"""


def main():
    page = PAGE.format(
        head=site_parts.head("About — bahansen.us",
                             "About bahansen.us and the Daily Security Intelligence Briefing.", depth=0),
        nav=site_parts.nav(depth=0, active="about"),
        footer=site_parts.footer(depth=0),
    )
    OUT.write_text(page)
    print(f"Wrote {OUT} ({len(page)} bytes)")


if __name__ == "__main__":
    main()
